var sources = [
    { name: 'blognone',             url: 'http://www.blognone.com/atom.xml' },
    { name: 'droidsans',            url: 'http://droidsans.com/rss.xml' },
    { name: 'macthai',              url: 'http://www.macthai.com/feed/' },
    { name: 'thumpsup.th',          url: 'http://thumbsup.in.th/feed' },
    { name: 'mobiledista',          url: 'http://mobiledista.com/feed' },
    { name: 'theverge',             url: 'http://www.theverge.com/rss/index.xml' },
    { name: 'engadget',             url: 'http://www.engadget.com/rss.xml' },
    { name: 'techchrunch',          url: 'http://feeds.feedburner.com/TechCrunch/' },
    { name: 'xda-developers',       url: 'http://www.xda-developers.com/feed' },
    { name: 'lifehacker',           url: 'http://feeds.gawker.com/lifehacker/full' },
    { name: 'cnet',                 url: 'http://www.cnet.com/rss/all/' },
    { name: 'gizmodo',              url: 'http://feeds.gawker.com/gizmodo/full' },
    { name: 'front-end dev weekly', url: 'http://frontenddevweekly.com/issues.rss', css: 'background-color: #fff9a5;' },
];
